window.onload = function() {
    // Teeme sõnaloendid globaalseks, et neid saaks pidevalt uuendada
var words1 = [
  "Aabraham", "Bileam", "Jefta",
  "Iisak", "kaev", "lammas",
  "laulma", "Aabel", "sõna",
  "suur kala", "siga", "deemonid",
  "toit", "Taavet", "vesi",
  "Joosua", "kuu", "poiss",
  "käsi", "kuld", "kits",
  "tütar", "Kain", "Simson",
  "Saul", "kõrb", "lootus",
  "Rebeka", "Saara", "Maarja",
  "Ester", "mesi", "töö",
  "metsloomad", "madu", "täht",
  "Eeva", "valgus", "õun",
  "Maarja", "silm", "ronk",
  "hobune", "Laulud", "Iiob",
  "tall", "suu", "veeuputus",
  "ema", "sõrm", "Noa",
  "suur lohe", "arbuus", "tiik",
  "paat", "Giideon", "lõvi",
  "kana", "Paulus", "kotkas",
  "Jehoova", "keerub", "rahu",
  "vikerkaar", "Saalomon", "Piibel",
  "Taaniel", "torn", "paradiis",
  "lapsed", "õhtu", "Aadam",
  "sipelgas", "palve", "Rutt",
  "puu", "Joona", "patt",
  "kuningas", "meri", "aamen",
  "eesel", "Koljat", "Saul",
  "Joosep", "Aaron", "riided",
  "Jeesus", "mees", "leib",
  "armastus", "päike", "naer",
  "kaamel", "kaev", "pimedus",
  "nutt", "kepp", "Matteus",
  "liiv", "Mooses", "lamp",
  "Leevi", "Iisebel", "maakera",
  "apostel", "Noomi", "Lott",
  "tuvi", "2. Ajaraamat", "kõrv",
  "halb", "sool", "hommik",
  "piim", "Peetrus", "varblane",
  "jõgi", "Kristus", "Iiob",
  "konnad", "liha", "Joonatan",
  "Iisai", "järv", "Markus",
  "Johannes", "Iisrael", "rohi",
  "kadedus", "päästja", "rada",
  "uss", "Jaakob", "messias",
  "Jumala nimi", "auline", "eeskuju",
  "imik", "rõõm", "süda",
  "veri", "vilistasid", "välk",
  "väle", "kuiv", "seeme",
  "nina", "muld", "ilus",
  "ahi", "aastaaeg", "leht",
  "täiskuu", "kuninganna", "naba",
  "pill", "arm", "lehm",
  "voodi", "tuvimaja", "sinikad",
  "hapu", "maja", "raha",
  "hallid juuksed", "vili", "telk",
  "tähnilised", "nägu", "janu",
  "magama", "lõhn", "vai",
  "ling", "kingitus", "vasar",
  "post", "tuul", "vana",
  "vihm", "tõrvik", "suur täht",
  "kõne", "kari", "post",
  "möll", "sarv", "õigus",
  "kari", "vaim", "ustav",
  "sõprus", "koer", "tuli",
  "auhind", "pääste", "Jumal",
  "juur", "ohakas", "sajakordne",
  "kõrvad", "vaenlane", "õnnetus",
  "hüppama", "kausike", "tee",
  "elu", "tõde", "häbi",
  "ingel", "talv", "suvi",
  "külm", "kuum", "oda"
];

    var words2 = [
  "Saamuel",
  "vana kuub",
  "tiivulised",
  "mõõgatorked",
  "Vahemeri",
  "Apostlite teod",
  "küüslauk",
  "5 arukat neitsit",
  "Noa laev",
  "toored viinamarjad",
  "Siisera",
  "laevatükid",
  "rahetorm",
  "veevool katkeb",
  "Maa püsib igavesti",
  "Jeeriko",
  "Eenok",
  "Petlemm",
  "Sekem",
  "nädalatepüha",
  "kuningriik",
  "Edom",
  "4026 e.m.a",
  "liisu heitmine",
  "mõistujutt",
  "Õlimägi",
  "meelelahutus",
  "Abisai",
  "Benjamin",
  "Moabimaa",
  "kuldvasikas",
  "ling",
  "vastupidavus",
  "paabulinnud",
  "kuivanud viigipuu",
  "õli",
  "Saagu valgus",
  "manna",
  "Ärge muretsege",
  "Raahel",
  "vaimumõõk",
  "Oobed",
  "maavärin",
  "korv",
  "mõttega lugema",
  "Jehu",
  "tessalooniklastele",
  "lõõmavad hobused",
  "pottsepp",
  "Jeesuse lunastusohver",
  "mandlipuu õitseb",
  "nälg",
  "kannatlik",
  "70 jüngrit",
  "gibeonlased",
  "truu armastus",
  "Bartolomeus",
  "Aakan varastab",
  "Siioni mägi",
  "surematus",
  "Jefta",
  "taimetoit armastusega",
  "sünnib Petlemmas",
  "raudkepp",
  "Ristija Johannes",
  "Taavet tantsib",
  "Pilaatus",
  "Naabal",
  "Damaskus",
  "teised lambad",
  "Siinai mägi",
  "peaingel",
  "Jeruusalemma müürid",
  "hea ja halva tundmise puu",
  "kogu südamest ja hingest",
  "sääsed",
  "Nebukadnetsar",
  "tiivad",
  "kesköö",
  "rauast sääred",
  "rebane",
  "tuvimüüjad",
  "12 kivi",
  "Talle pulmad",
  "koguduseabiline",
  "janusena postil",
  "tänulik pidalitõbine",
  "järeltulija",
  "Johannes",
  "Aamos",
  "Kyros",
  "metsalise kuju",
  "Sakarja",
  "Jesaja prohvetikuulutus",
  "püha vaimu vilja tahud",
  "alfa ja oomega",
  "lohe",
  "ingel",
  "haputainas",
  "varas öösel",
  "Miikal",
  "Daan",
  "trepp",
  "Andreas",
  "sikk",
  "elupuu",
  "Naatanael",
  "ingel Gaabriel",
  "Naaman",
  "leviit",
  "esmatähtis",
  "rullraamat",
  "hiiglased",
  "veri uksepiitadel",
  "Lea ja Raahel",
  "põlevad nooled",
  "Gomorra",
  "Ai linn",
  "inimesepoeg",
  "Orpa",
  "Kaaleb",
  "mägi suitseb",
  "viigimarjapätsike",
  "aare savinõudes",
  "Juudas Iskariot",
  "Filippus",
  "noor Timoteos",
  "ebajumal",
  "Mordokai",
  "Keefas",
  "manna kõrbes",
  "koloslastele",
  "aeg rääkida",
  "mõistuse seadus",
  "Korneelius perega",
  "Ruuben",
  "Jaafet",
  "allumine",
  "3 meetrit pikk",
  "Jaakob",
  "Malaki",
  "unenägu",
  "Diina",
  "suur torm",
  "Saagu valgus",
  "Lea",
  "Maarja Magdaleena",
  "Jael",
  "eluvesi",
  "hing",
  "Madu pettis mind",
  "vastpöördunu",
  "nasiir",
  "ime",
  "joogiohver",
  "Ketuura",
  "piim ja mesi",
  "neli inglit",
  "tempel",
  "töölesundijad",
  "Eenok",
  "Marta",
  "seitse trompetit",
  "Ma ei naernud",
  "šaakal",
  "speltanisu",
  "Nimrod",
  "Absalom",
  "auhiilgus",
  "kõhus kibe",
  "Püsigem ärkvel",
  "70 aastanädalat",
  "veskikivi",
  "teine surm",
  "ülevaataja",
  "Suur Babülon",
  "Metuusala",
  "Lemek",
  "tasuta juua",
  "tulejärv",
  "mullaks sa saad",
  "Euodia",
  "Egiptus",
  "elupuu",
  "Egiptuse vaarao",
  "Assur",
  "ike",
  "viinamari",
  "Rooma",
  "Täitke maa...",
  "odralõikus",
  "lapsed kurjuses",
  "küljeluu",
  "Naatan",
  "Dorkas",
  "tõde",
  "surutõrs",
  "turteltuvid",
  "misjonär",
  "kaastöölised",
  "pärdikud",
  "kana kogub tibud",
  "seeravid",
  "kuke kiremine",
  "Suusa",
  "kuulutamine",
  "pilliroog",
  "607 e.m.a",
  "mälestusraamat",
  "Hesekiel",
  "Eesav",
  "merelaine",
  "Jordan",
  "Zeus",
  "õepoeg Markus",
  "rinnakilp",
  "Jehoova on armastus",
  "sinepiseema",
  "vutt",
  "filiplastele",
  "arst Luukas",
  "rikas",
  "filosoofia",
  "Raahab",
  "rohutirtsud",
  "jooksmine",
  "Nehemja",
  "vibu",
  "hea sõnum",
  "hundid lambanahas",
  "Pootifar",
  "mälestusõhtu",
  "okaskroon",
  "jaanalind",
  "headus",
  "Siilo",
  "Haam",
  "Mirjam",
  "tõevöö",
  "Jaah",
  "Apollos",
  "Tiitus",
  "Taaniel lõvide augus",
  "kalur",
  "muul",
  "mürk",
  "Ilmutuse raamat",
  "Gaad",
  "tulipunane lohe",
  "vahimees",
  "Stefanos",
  "kogudusetelk",
  "kobra",
  "Hoosea",
  "väike kari",
  "ihaldusväärne",
  "põlev põõsas",
  "aeg istuda",
  "maksude maksmine",
  "ristimine",
  "jänes",
  "karu",
  "Joosija",
  "õlipuuleht",
  "parmud",
  "Fileemon",
  "suur viletsus",
  "Bileam",
  "lilled",
  "halb variser",
  "sünagoog",
  "lehm",
  "Herodes",
  "Absalom",
  "eluraamat",
  "Jaakobus",
  "lõke",
  "koduloomad",
  "patud on erepunased",
  "Abigail",
  "Deliila",
  "puudesalu",
  "papüürus",
  "Sett",
  "sälg",
  "laisk ori",
  "iisop",
  "Uurija",
  "keerubid",
  "JHVH",
  "toonekurg",
  "eluleib",
  "valetamine",
  "Seeba kuninganna",
  "Moosese seadus",
  "preester",
  "järelnoppimine",
  "Jumala ilmutus",
  "muulane",
  "vaskmadu",
  "lõuna kuningas",
  "Eeli",
  "Seem",
  "ratsanik",
  "andestan",
  "Juuda",
  "inimesekartus",
  "kuulekus",
  "halb seltskond",
  "püha vaim",
  "Batseba",
  "Abner",
  "40 päeva",
  "Piinehas",
  "pull",
  "efeslastele",
  "Galilea",
  "valeprohvet",
  "metsaline",
  "süütud nagu tuvid",
  "Harmagedoon",
  "Soolameri",
  "juuksekarvad",
  "karikas",
  "purjetamine",
  "Laaban",
  "Jerobeam",
  "Siimeon",
  "Matteus",
  "vend Juudas",
  "Toomas",
  "Boas",
  "kadunud lammas",
  "Abinadab",
  "piik",
  "maksukoguja",
  "kristlased",
  "Niineve",
  "Punane meri",
  "1000 aastat",
  "usukilp",
  "Sippora",
  "Huur",
  "Betsaleel",
  "Huusai",
  "Saulus",
  "Miika",
  "Uri linn",
  "Juuda",
  "Samaaria",
  "rusuhunnik",
  "rahva juhid",
  "igaüks",
  "vilistid",
  "Amnon",
  "Samma",
  "päevad on kurjad",
  "halastus",
  "kõiksugused inimesed",
  "hea südametunnistus",
  "suguvõsa",
  "nöörlood",
  "nikerdatud kuju",
  "kogenematud lähevad edasi",
  "Betuel",
  "ärge ärritage",
  "koi ja rooste",
  "armetu inimene",
  "üürielamu",
  "õieke",
  "Sina üksi",
  "erapoolik",
  "otsuseorg",
  "kaks hooranaist",
  "puhtad ajendid",
  "Haagar",
  "Ismael",
  "Ketuura",
  "Baalak",
  "Süüria",
  "Meedia",
  "Ruuben",
  "kohaloleku tundemärk",
  "Gehenna",
  "Septuaginta",
  "tõotatud maa",
  "hautisepott",
  "Mefiboset",
  "Abiram",
  "Ei anna alla",
  "meeldiv",
  "patu seadus",
  "Jeremija",
  "Lüüdia",
  "taht",
  "harjutamise teel treenimine",
  "Joppe",
  "ülikud",
  "vabastusaasta",
  "jebuuslased",
  "Kapernauma",
  "ebaaus tulu",
  "keha treenimine",
  "seitse aega",
  "pisarad",
  "sõnaosav",
  "Kiis",
  "pelikan",
  "mürr",
  "vaskmeri",
  "tulevane elu",
  "Betsata tiik",
  "Tüüros",
  "puhkepaik",
  "Antiookia",
  "figuur",
  "nahast piimalähker",
  "käsi põues",
  "luurajad",
  "tamburiin",
  "suudlema",
  "vahionn",
  "lehvivad juuksed",
  "kurgipõld",
  "Justus",
  "lüüra",
  "piiramisrõngas",
  "püha mägi",
  "kullasepp",
  "aganad",
  "alusrõivas",
  "Aramea",
  "asasel",
  "batt",
  "Dekapolis",
  "ülesminekulaulud",
  "Hermes",
  "Tühi ja lage",
  "vetesügavus",
  "esimene päev",
  "koondunud veed",
  "proselüüt",
  "peltsebul",
  "sekt",
  "See oli väga hea",
  "kaarik",
  "vanne",
  "täiendus",
  "viljapeks",
  "Kolgata",
  "suulamlanna",
  "Karmel",
  "Hanna",
  "sinepiseeme",
  "alabasterpudel",
  "Areopaag",
  "Dareios",
  "Beltsassar",
  "Belsatsar",
  "juudi mehe kuub",
  "puu eluiga",
  "seeme tee ääres",
  "rändur",
  "peigmees",
  "Mattias",
  "maskil",
  "Gilead",
  "tumm Sakarjas",
  "Immaanuel",
  "kaduvuse orjus",
  "kõigekõrgema prohvet",
  "Jairus",
  "Sühhari linn",
  "käimla",
  "pesemata kätega söömine",
  "Nikodeemos",
  "paindlik",
  "Eliihu",
  "õhusuudlus",
  "lõunamaa kuninganna",
  "see põlvkond",
  "rästikute sugu",
  "uuesti sündima",
  "paljusid asju õpetama",
  "avaldama",
  "püha saladus",
  "ilmaaegu",
  "pöörduma",
  "teeäärne pinnas",
  "umbrohi",
  "tähekriipsuke",
  "aiataimed",
  "seaa",
  "rändkaupmees",
  "igasugused kalad",
  "tulekolle",
  "Uut ja vana",
  "puusepa poeg",
  "kodukant",
  "neli vankrit",
  "Võsu",
  "ülim isand",
  "lepingu saadik",
  "taevaluugid",
  "Jehoova tundmine",
  "Joosafat",
  "kroonikaraamat",
  "mälestus",
  "püha tee",
  "nimekad mehed",
  "häbitunne",
  "mässumeelsus",
  "võitma usule",
  "kadumatu ilu",
  "vooruslikkus",
  "algõpetus",
  "vundament",
  "röövlind",
  "päikesetõus",
  "peab vastu kõiges",
  "usub kõike",
  "toitu ostma",
  "täiel määral",
  "viivitamata",
  "Beroia",
  "siiras usk",
  "Teda kuulake",
  "lõplik võit",
  "surma maitsma",
  "keelas kõvasti",
  "määratud aeg",
  "igavik südames",
  "rahvavanemad",
  "residents",
  "asjatundja",
  "uus laul",
  "Siilas",
  "korraldus",
  "palvekoda",
  "suur pilv tunnistajaid",
  "võidujooks",
  "eesootav rõõm",
  "põhitõed",
  "piim ja tahke toit",
  "Jaabin",
  "Etteheiteid tegemata",
  "usu tõttu",
  "valged rüüd",
  "mõõtmatu",
  "põrm",
  "teab hästi",
  "hädaaeg",
  "Sinu sõna peale",
  "Ära karda",
  "On oma kohtadel",
  "Jumala seatuna",
  "eestvedajad",
  "allutama",
  "Iisraeli püha",
  "arukus",
  "arvutama",
  "666",
  "saate tõeliselt vabaks",
  "teraselt vaatama",
  "täiuslik seadus",
  "Kaisarea",
  "mägismaa",
  "inimsüda",
  "ülimalt õnnistatu",
  "Jehoova orjatar",
  "leopard",
  "Elatanu",
  "Sarv rääkis",
  "tervituse hääl",
  "Isanda ema",
  "tuvipoeg",
  "vastsündinu",
  "šaakalid",
  "žestid",
  "Akvila",
  "külitama",
  "lõid käed",
  "palehigis",
  "Uus Jeruusalemm",
  "tollihoone",
  "mereloomad",
  "laubavõru",
  "sajapealikud",
  "käekäik",
  "elavate maa",
  "meeleheide",
  "valearutlused",
  "korra kummardad",
  "mõtlemisoskus",
  "lugupidamatu",
  "haistma",
  "lehviv lakk",
  "vägevus",
  "kartmatud",
  "deemonite sõnumid",
  "Ärge imestage",
  "kohkuma",
  "noor tugev lõvi",
  "neitsilik tütar",
  "kustutamatu tuli",
  "judaism",
  "kodakondsus",
  "rusutud",
  "rõõmus süda",
  "alati pidu",
  "hea maa",
  "telgitegijad",
  "koormaloom",
  "pesakond",
  "sähviv tuli",
  "sädelev jää",
  "ämm",
  "minia",
  "raju",
  "kaks leptonit",
  "mõõtmatu",
  "goferipuu",
  "koormavad lohutajad",
  "salv",
  "ait",
  "teised rahvad",
  "silmapiir",
  "säästma",
  "vastupanija",
  "taevased paigad",
  "koosseis",
  "energia",
  "äravalitud",
  "uueksloomine",
  "rabatud",
  "Kreeta",
  "Kõuepojad",
  "ilmalik",
  "sirutab tiivad",
  "täielik rõõm",
  "väljuv jõud",
  "teie päralt",
  "kindel alus",
  "vendade süüdistaja",
  "tähekriipsuke",
  "põhimõte",
  "avalik",
  "eriline omand",
  "hoiatav näide",
  "Patmos",
  "fakt",
  "majaperenaine",
  "aianuga",
  "viimseil päevil",
  "viimseil päevil",
  "patte kahetsema",
  "tõeline elu",
  "sõitlema",
  "vaistlikult",
  "veeta pilved",
  "vandenõu",
  "Ismael",
  "veemahuti",
  "üürike aega",
  "hiidtürannid",
  "verepõld",
  "asendama",
  "kosutuse ajad",
  "Oma õpetus",
  "Safiira",
  "hajutama",
  "ahtake värav",
  "isakodu",
  "ärakiri",
  "salakaval",
  "siirus",
  "selgitades loogiliselt",
  "niinimetatud"
];

    var words3 = [
  "Sifra", "veadar", "Baesa", "Puua", "Barabas", "Nebo mägi", "Billa", "Joas", 
  "kahe sarvega jäär", "Silpa", "Ooded", "krüsoliit", "Pöörduge tagasi Jehoova juurde", 
  "rästik hammustab Paulust", "Noa läks perega laeva", "Hofni", "Sebulon", "Megiddo mägi", 
  "Susanna", "Johanna", "Ohola", "Lappidot", "Aviv", "Oholiba", "Roode", "Tiglatpilesar", 
  "idavärav", "Gomer", "Lo-Ruhama", "Lo-Ammi", "Keha lamp on silm", "Pärsia kuningas Ahasveros", 
  "Rebeka joodab kaameleid", "nahaparkija", "Teofilos", "Joppe", "lesknaine ja kohtunik", 
  "vangla uksed avanevad", "Ma Saan, Kelleks Ma Tahan", "kuningriigileping", "Atalja", 
  "Saalemi kuningas", "sükomoor-viigipuu", "Selofhad", "Tirsa", "Söö ära see rullraamat", 
  "Olendites tegutsev vaim oli ka rattais", "Päike muutub pimedaks ja kuu vereks", 
  "leegina pöörlev mõõk", "mäest murti lahti kivi", "Raahabi punane köis", 
  "hingamispäeva isand", "Peetrus kõnnib vee peal", "preester Melkisedek", 
  "kohtumõistja Jefta tütar", "70 nädalat, et  lepitada süü", "aeg, kaks aega ja pool aega", 
  "Sanhedrin", "rudjutud pilliroog", "Johannese 3 kirja", "kreekakeelne Septuaginta", 
  "Teie vennaarmastus jäägu püsima", "viigimarjade vääristaja", "uus leping", "pudelkõrvits", 
  "Jumala rahu kaitseb", "Silvaanus", "Emmause tee", "Baarak", "naisprohvet Anna", 
  "kulumatud kukrud", "vaim ja pruut", "Deemas", "Siiloahi tiik", "Hermoni mägi", 
  "hõbe ja kuld ei päästa", "Häda maale ja merele", "ettevaatlikud nagu maod", 
  "Kaana", "rabbuuni", "sündinud pühade ajal", "Ahitofel", "minu saadik", "Eutühhos", 
  "Hilkija", "Piison (jõgi)", "10 sarve ja 7 pead", "Euodia ja Süntühhe", "Drusilla", 
  "teeravikujud", "õiguse rinnaturvis", "Nuuni poeg Hosea", "kuningas Hosea", 
  "Jehoova poole palvetama", "Joona palvetab kala kõhus", "ülempreester Hananias", 
  "Antiookia", "Hümenaios", "hallel-laulud", "Eljasib", "Tertullus", "Nain", 
  "Issaskar", "pitser laubal", "Tüüros", "viinamäe töölised", "õiged ja ülekohtused", 
  "Felix", "Naisprohvet Deboora", "Kaanan", "Hiddekel", "Makedoonia", "Betuel", 
  "Artaxerxes", "Gamaaliel", "Agrippa", "Mamre", "hülgenahkadest kate", 
  "patt luurab ukse taga", "surnute ülestõusmine", "hea südametunnistus", "Abimelek", 
  "Festus", "kristallselge eluveejõgi", "Menee, menee, tekeel, parsiin", 
  "Saatan 1000 aastat vangis", "Taamar", "Kedorlaomer", "Aaser", "pärg 12 tähest", 
  "Serubbaabel", "Menahem", "Betaania", "käsn iisopivarre otsas", "pime Bartimeus", 
  "karvane sikk", "Tüatiira linn", "tuhkur hobune", "Midjani preester", "Hulda", 
  "Keedar", "metsaline hakkab prostituuti vihkama", "Kyrose korraldus ehitada Jumala koda", 
  "leopard lesib kitsekese kõrval", "Naftali", "läbiproovitud usk", "Rehabeam", 
  "600 sõjavankrit", "võitja valgel hobusel", "Oneesimos", "kastepiisad koidu üsas", 
  "veeojade äärde istutatud puu", "armastus on kui Jaahi tulelõõm", "töölise päevapalk denaar", 
  "tema purustab su pea", "armastus ei taotle omakasu", "kiire ei võida alati jooksu", 
  "naisele anti kotka tiivad", "Tüürose kuningas Hiiram", "Iisboset", "Taddeus", 
  "Oholiab", "Gati kuningas", "Aakis", "Abisag", "Efrata", "Jootam", 
  "maa püsib igavesti", "Ärgem  loobugem head tegemast", "Nõrkadele olen ma nõrk", 
  "Tagasihoidlikel on tarkus", "Külva Jumala vaimule", "Sittim", "Siihon", "Simei", 
  "Laastaja tuleb jälkuste tiibadel", "Nädala keskel kaotab ta ohvrianni", 
  "Kittimi laevad", "Taiplikud säravad otsekui tähed", "linastes riietes mees jõe kohal", 
  "Mestis Iisai pojaga", "Agag", "Kyros vabastab iisraellased", "Meseki ja Tubali kõrgeim pealik", 
  "Semaja", "Gerar", "Ben-Ooni", "Neid päevi vähendatakse", "Reuel", 
  "Vaadake, et te kartma ei löö", "Kleopas", "Joojada", "elupuu juurde viiv tee", 
  "Aada", "jalad nagu tulesambad", "Jooseba", "Ei tehta kurja ega kahju", "Oon", 
  "Joosese ema Maarja", "Saloome", "metsikud ürtarbuusid", "Tarsis", "Claudius", 
  "Ben-Hadad", "hõbe ja kuld ei päästa", "Häda maale ja merele", "ettevaatlikud nagu maod", 
  "suunemlanna", "Hatak", "Memukan", "eunuhh", "viigilehtedest niudevöö", 
  "Demeetrios", "Artemis", "Gaius", "pärandi tagatis", "Ustav ja tõeline", 
  "Langege meie peale", "Abaddon", "Idumea", "pojal on vägi anda elu", 
  "sina üksi oled kõrgeim üle kogu maa", "Kogu pühakiri on Jumalalt", 
  "riputab maa eimillegi kohale", "Sebah ja Salmuna", "Lüstra", "Foibe", 
  "põhjendatud ootus, et loodetav saab tõeks", "teil tuleb hoiduda verest", 
  "Ärge summutage Jumala vaimu tuld", "te kõik olete valguse ja päeva pojad", 
  "mida inimmõistus ei suuda haarata", "kuulutatakse tunnistuseks kõigile rahvastele", 
  "mägi tõuseb kõrgemale küngastest", "Mulle tuli taas Jehoovalt sõnum", 
  "Jumala laste võrratu vabadus", "Ärge laske röövida endalt auhinda", "Kapadookia", 
  "Innukus su koja pärast põleb mu sees", "kiirustab lõpu poole", "määratud niiviisi lagunema", 
  "Inimesepoja kohaloleku aeg", "süda on tuimaks läinud", "linnud leiavad elupaiga okste vahel", 
  "Lõikajad on inglid", "säravad nagu päike", "Pange mind proovile",
  "süüdi igaveses patus",
  "veed katavad merepõhja",
  "Beliar",
  "Vahemees Jumala ja inimeste vahel",
  "Betfages",
  "Effata!",
  "Tuleb Jehoova nimel",
  "Juuda tuhandete seas",
  "Antipas",
  "kuulutamist seadustama",
  "elame, liigume ja oleme olemas",
  "sõnadest lõksu püüdma",
  "Sebna",
  "mõistis maailma süüdi",
  "Pääste me võlgneme",
  "Genneesareti järv",
  "Valvavad teie järele",
  "Läheb vaja tarkust",
  "Allutatud tühisusele",
  "Abija teenistusrühm",
  "Vähesest saab tuhat",
  "Sa lähed Jehoova ees",
  "võida kõige püham paik",
  "Heldai",
  "Toobia",
  "Jedaja",
  "Hoiablepingut jõus veel ühe nädala",
  "7 nädalat ja veel 62 nädalat",
  "Jehoova tõttab sellega omal ajal",
  "Zeenas",
  "Šaul",
  "Quirinius",
  "Nooled sangari käes",
  "Nähtamatu Jumala peegeldus",
  "See kel on mõjuvõimu",
  "Jõu ja kaine mõistuse vaim",
  "Mida saab inimene mulle teha?",
  "suur põlev mägi",
  "metsalise märk",
  "varustusevalvur",
  "kõigest pole kasu",
  "julge ja hästi tugev",
  "Valmidus kuulutada head sõnumit rahust",
  "Meeros",
  "Liisuosa päevade lõpus",
  "Miikaja",
  "Naerab hirmu üle",
  "pole teadmisi ega tarkust",
  "Toetub inimkäele",
  "Herodias",
  "ristib püha vaimu ja tulega",
  "Arpaksad",
  "Serah",
  "pidagu sügavalt lugu",
  "Täidab Jumala tahet",
  "Käsitleb tõe sõna õigesti",
  "vastu pidades vilja kannavad",
  "Diotrefes",
  "kõrgus ega sügavus",
  "kuningriigi võtmed",
  "kutsun päikesetõusu poolt röövlinnu",
  "kuulutan millega asjad lõppevad",
  "ammusest ajast",
  "variseride juuretis",
  "kõike seda muud antakse teile",
  "teise vahikorra ajal",
  "valmistab katsumuse korral väljapääsu",
  "ei otsi austust inimestelt",
  "pärib teilt teie lootuse kohta",
  "võtted pole meile teadmata",
  "kolmandik taevatähtedest",
  "Poeg allutab end Jumalale",
  "Ärge petke end",
  "ustavad selle maailma vara kasutamises",
  "elab igavesest ajast igavesti",
  "vangistame iga mõtte",
  "must mooruspuu",
  "Kasvata meie usku",
  "Sinu usk on sind terveks teinud",
  "sadas tuld ja väävlit",
  "pearahamaks",
  "paneb õiguse võidutsema",
  "Trüfaina",
  "isandate isand",
  "kuningate kuningas",
  "rahvastele määratud ajad",
  "Olge alati rõõmsad",
  "Alfeus",
  "Taeva vägesid kõigutatakse",
  "mere möirgamine",
  "olukorrast väljapääsu",
  "Kasvavad koos lõikuseni",
  "Võtke oma koht sisse",
  "seiske ja vaadake, kuidas Jehoova teid päästab",
  "Kristusega seadus lõppes",
  "jäädav vägi ja jumalikkus",
  "Massa ja Meriba",
  "hea, meeldiv ja täiuslik",
  "imelise lootuse täitumine",
  "Vastab enne faktide ärakuulamist",
  "Siiba",
  "Jehoova soosingu aasta",
  "templipühitsemispüha",
  "Tuleb öö, mil keegi ei saa midagi teha",
  "Toida mu lambakesi",
  "inimene on valitsenud inimese üle",
  "ühtsuse täiuslik side",
  "Kes hüüab appi Jehoova nime, päästetakse",
  "on iga maja kellegi ehitatud",
  "Amittai",
  "õiguse parema käega",
  "peitis end ära",
  "läksie vaatama",
  "tõesti leiaksid ta",
  "suurima patuse näite varal",
  "Ei suuda meid lahutada Jumala armastusest",
  "Diotrefes",
  "käesolev ega tulev",
  "mistahes muu loodu",
  "kui ma kuulen oma lapsi tõeteel käivat",
  "Ebed-Melek",
  "Nebusaradan",
  "Alguses lõi Jumal taeva ja maa",
  "tulen kiiresti",
  "Isand Jeesus Kristuse arm olgu pühadega!",
  "Jisreel",
  "Ärge kaotage julgust",
  "Ole julge ja tugev",
  "Ustavale oled sa ustav",
  "Barsillai",
  "tuleb aeg, ja see ongi juba käes",
  "Epafras",
  "veel julgemad, jah, kartmatud",
  "Seres",
  "Hadassa",
  "Tiberiase meri",
  "Sebedeus",
  "Justus",
  "Kidroni org",
  "Jumal on teinud ta nii isandaks kui ka messiaks",
  "imelise valguse käes",
  "Olete täitnud Jeruusalemma",
  "Eela org",
  "Heebrea keelt kõnelevad juudid",
  "Keel on tuli",
  "Gaza",
  "Pole nendega mingit pistmist"];

// Globaalsed muutujad valitud sõna jaoks
var number;
var selectedWordsList;
var lastSelectedList; // See muutuja jälgib, millisest loendist viimane sõna valiti.
var punktid1;
    var punktid2;
    var punktid3;
    var punktid4;
    var punktid5;
    var punktid6;
    var punktid7;
    var punktid8;
    var punktid9;
    var punktid10;
    var punktid11;

// Funktsioon kergete sõnade jaoks
function kerged() {
  if (words1.length > 0) {
    number = Math.floor(Math.random() * words1.length);
    selectedWordsList = words1;
    lastSelectedList = 'kerged'; // Määrame viimaseks valikuks 'kerged'
    document.getElementById("word").textContent = words1[number];
  } else {
    document.getElementById("word").textContent = "Kerged sõnad on otsas!";
  }
}

// Funktsioon keskmiste sõnade jaoks
function keskmised() {
  if (words2.length > 0) {
    number = Math.floor(Math.random() * words2.length);
    selectedWordsList = words2;
    lastSelectedList = 'keskmised'; // Määrame viimaseks valikuks 'keskmised'
    document.getElementById("word").textContent = words2[number];
  } else {
    document.getElementById("word").textContent = "Keskmised sõnad on otsas!";
  }
}

// Funktsioon raskete sõnade jaoks
function rasked() {
  if (words3.length > 0) {
    number = Math.floor(Math.random() * words3.length);
    selectedWordsList = words3;
    lastSelectedList = 'rasked'; // Määrame viimaseks valikuks 'rasked'
    document.getElementById("word").textContent = words3[number];
  } else {
    document.getElementById("word").textContent = "Rasked sõnad on otsas!";
  }
}

// Funktsioon sõna eemaldamiseks ja uue valimiseks
function tehtud() {
  if (selectedWordsList && number !== undefined) {
    selectedWordsList.splice(number, 1); // Eemaldame valitud sõna loendist

    // Eemaldame kõik olemasolevad taustavärvi klassid body'lt või tausta elemendilt
    document.body.classList.remove('kerged-bg', 'keskmised-bg', 'rasked-bg');

    // Otsi taustaga element ID põhjal
    const background = document.getElementById('background');

    // Kui background-element eksisteerib
    if (background) {
      background.classList.remove('kerged-bg', 'keskmised-bg', 'rasked-bg'); // Eemaldame olemasolevad klassid

      // Kontrollime, millisest loendist viimane sõna oli ja muudame taustavärvi
      if (lastSelectedList === 'kerged') {
        kerged(); // Käivitame uuesti funktsiooni kerged
        background.classList.add('kerged-bg'); // Muudame taustavärvi roheliseks
      } else if (lastSelectedList === 'keskmised') {
        keskmised(); // Käivitame uuesti funktsiooni keskmised
        background.classList.add('keskmised-bg'); // Muudame taustavärvi siniseks
      } else if (lastSelectedList === 'rasked') {
        rasked(); // Käivitame uuesti funktsiooni rasked
        background.classList.add('rasked-bg'); // Muudame taustavärvi punaseks
      }
    } else {
      console.error("Element with ID 'background' not found.");
    }
  } else {
    document.getElementById("word").textContent = "Pole sõna, mida eemaldada!";
  }
}

    const display = document.getElementById("display");
    let timer = 0;
    let startTime = 0;
    let remainingTime = 90000; // 1 minut ja 30 sekundit millisekundites
    let isRunning = false;

    function start() {
        if (!isRunning && remainingTime > 0) {
            startTime = Date.now();
            timer = setInterval(update, 10);  // Kontrollime iga 10ms järel, et uuendada kuva
            isRunning = true;
        }
    }

    function stop() {
        if (isRunning) {
            clearInterval(timer);
            remainingTime -= Date.now() - startTime;
            isRunning = false;
        }
    }

    function reset() {
        clearInterval(timer);
        remainingTime = 90000; // 1 minut ja 30 sekundit
        isRunning = false;
        display.textContent = "01:30"; // Algväärtus kuvatakse
    }

    function update() {
        const currentTime = Date.now();
        const elapsed = currentTime - startTime;

        const timeLeft = remainingTime - elapsed; // Arvutame, kui palju aega on alles

        if (timeLeft <= 0) {
            clearInterval(timer);
            display.textContent = "00:00"; // Kui aeg saab otsa, näitame nulli
            isRunning = false;
            return;
        }

        let minutes = Math.floor(timeLeft / (1000 * 60) % 60);
        let seconds = Math.floor(timeLeft / 1000 % 60);

        minutes = String(minutes).padStart(2, "0");
        seconds = String(seconds).padStart(2, "0");

        display.textContent = `${minutes}:${seconds}`;
    }

    // Sidume nupud sündmuste külge
    document.getElementById("startBtn").onclick = start;
    document.getElementById("stopBtn").onclick = stop;
    document.getElementById("resetBtn").onclick = reset;
    document.getElementById("kergeBtn").onclick = kerged;
    document.getElementById("keskmineBtn").onclick = keskmised;
    document.getElementById("raskeBtn").onclick = rasked;
    document.getElementById("yes").onclick = tehtud;
};
    function gem1() {

        punktid1++
        
    }