export const words3 = [
    "Sifra", "veadar", "Baesa", "Puua", "Barabas", "Nebo mägi", "Billa", "Joas", 
    "kahe sarvega jäär", "Silpa", "Ooded", "krüsoliit", "Pöörduge tagasi Jehoova juurde", 
    "rästik hammustab Paulust", "Noa läks perega laeva", "Hofni", "Sebulon", "Megiddo mägi", 
    "Susanna", "Johanna", "Ohola", "Lappidot", "Aviv", "Oholiba", "Roode", "Tiglatpilesar", 
    "idavärav", "Gomer", "Lo-Ruhama", "Lo-Ammi", "Keha lamp on silm", "Pärsia kuningas Ahasveros", 
    "Rebeka joodab kaameleid", "nahaparkija", "Teofilos", "Joppe", "lesknaine ja kohtunik", 
    "vangla uksed avanevad", "Ma Saan, Kelleks Ma Tahan", "kuningriigileping", "Atalja", 
    "Saalemi kuningas", "sükomoor-viigipuu", "Selofhad", "Tirsa", "Söö ära see rullraamat", 
    "Olendites tegutsev vaim oli ka rattais", "Päike muutub pimedaks ja kuu vereks", 
    "leegina pöörlev mõõk", "mäest murti lahti kivi", "Raahabi punane köis", 
    "hingamispäeva isand", "Peetrus kõnnib vee peal", "preester Melkisedek", 
    "kohtumõistja Jefta tütar", "70 nädalat, et  lepitada süü", "aeg, kaks aega ja pool aega", 
    "Sanhedrin", "rudjutud pilliroog", "Johannese 3 kirja", "kreekakeelne Septuaginta", 
    "Teie vennaarmastus jäägu püsima", "viigimarjade vääristaja", "uus leping", "pudelkõrvits", 
    "Jumala rahu kaitseb", "Silvaanus", "Emmause tee", "Baarak", "naisprohvet Anna", 
    "kulumatud kukrud", "vaim ja pruut", "Deemas", "Siiloahi tiik", "Hermoni mägi", 
    "hõbe ja kuld ei päästa", "Häda maale ja merele", "ettevaatlikud nagu maod", 
    "Kaana", "rabbuuni", "sündinud pühade ajal", "Ahitofel", "minu saadik", "Eutühhos", 
    "Hilkija", "Piison (jõgi)", "10 sarve ja 7 pead", "Euodia ja Süntühhe", "Drusilla", 
    "teeravikujud", "õiguse rinnaturvis", "Nuuni poeg Hosea", "kuningas Hosea", 
    "Jehoova poole palvetama", "Joona palvetab kala kõhus", "ülempreester Hananias", 
    "Antiookia", "Hümenaios", "hallel-laulud", "Eljasib", "Tertullus", "Nain", 
    "Issaskar", "pitser laubal", "Tüüros", "viinamäe töölised", "õiged ja ülekohtused", 
    "Felix", "Naisprohvet Deboora", "Kaanan", "Hiddekel", "Makedoonia", "Betuel", 
    "Artaxerxes", "Gamaaliel", "Agrippa", "Mamre", "hülgenahkadest kate", 
    "patt luurab ukse taga", "surnute ülestõusmine", "hea südametunnistus", "Abimelek", 
    "Festus", "kristallselge eluveejõgi", "Menee, menee, tekeel, parsiin", 
    "Saatan 1000 aastat vangis", "Taamar", "Kedorlaomer", "Aaser", "pärg 12 tähest", 
    "Serubbaabel", "Menahem", "Betaania", "käsn iisopivarre otsas", "pime Bartimeus", 
    "karvane sikk", "Tüatiira linn", "tuhkur hobune", "Midjani preester", "Hulda", 
    "Keedar", "metsaline hakkab prostituuti vihkama", "Kyrose korraldus ehitada Jumala koda", 
    "leopard lesib kitsekese kõrval", "Naftali", "läbiproovitud usk", "Rehabeam", 
    "600 sõjavankrit", "võitja valgel hobusel", "Oneesimos", "kastepiisad koidu üsas", 
    "veeojade äärde istutatud puu", "armastus on kui Jaahi tulelõõm", "töölise päevapalk denaar", 
    "tema purustab su pea", "armastus ei taotle omakasu", "kiire ei võida alati jooksu", 
    "naisele anti kotka tiivad", "Tüürose kuningas Hiiram", "Iisboset", "Taddeus", 
    "Oholiab", "Gati kuningas", "Aakis", "Abisag", "Efrata", "Jootam", 
    "maa püsib igavesti", "Ärgem  loobugem head tegemast", "Nõrkadele olen ma nõrk", 
    "Tagasihoidlikel on tarkus", "Külva Jumala vaimule", "Sittim", "Siihon", "Simei", 
    "Laastaja tuleb jälkuste tiibadel", "Nädala keskel kaotab ta ohvrianni", 
    "Kittimi laevad", "Taiplikud säravad otsekui tähed", "linastes riietes mees jõe kohal", 
    "Mestis Iisai pojaga", "Agag", "Kyros vabastab iisraellased", "Meseki ja Tubali kõrgeim pealik", 
    "Semaja", "Gerar", "Ben-Ooni", "Neid päevi vähendatakse", "Reuel", 
    "Vaadake, et te kartma ei löö", "Kleopas", "Joojada", "elupuu juurde viiv tee", 
    "Aada", "jalad nagu tulesambad", "Jooseba", "Ei tehta kurja ega kahju", "Oon", 
    "Joosese ema Maarja", "Saloome", "metsikud ürtarbuusid", "Tarsis", "Claudius", 
    "Ben-Hadad", "hõbe ja kuld ei päästa", "Häda maale ja merele", "ettevaatlikud nagu maod", 
    "suunemlanna", "Hatak", "Memukan", "eunuhh", "viigilehtedest niudevöö", 
    "Demeetrios", "Artemis", "Gaius", "pärandi tagatis", "Ustav ja tõeline", 
    "Langege meie peale", "Abaddon", "Idumea", "pojal on vägi anda elu", 
    "sina üksi oled kõrgeim üle kogu maa", "Kogu pühakiri on Jumalalt", 
    "riputab maa eimillegi kohale", "Sebah ja Salmuna", "Lüstra", "Foibe", 
    "põhjendatud ootus, et loodetav saab tõeks", "teil tuleb hoiduda verest", 
    "Ärge summutage Jumala vaimu tuld", "te kõik olete valguse ja päeva pojad", 
    "mida inimmõistus ei suuda haarata", "kuulutatakse tunnistuseks kõigile rahvastele", 
    "mägi tõuseb kõrgemale küngastest", "Mulle tuli taas Jehoovalt sõnum", 
    "Jumala laste võrratu vabadus", "Ärge laske röövida endalt auhinda", "Kapadookia", 
    "Innukus su koja pärast põleb mu sees", "kiirustab lõpu poole", "määratud niiviisi lagunema", 
    "Inimesepoja kohaloleku aeg", "süda on tuimaks läinud", "linnud leiavad elupaiga okste vahel", 
    "Lõikajad on inglid", "säravad nagu päike", "Pange mind proovile",
    "süüdi igaveses patus",
    "veed katavad merepõhja",
    "Beliar",
    "Vahemees Jumala ja inimeste vahel",
    "Betfages",
    "Effata!",
    "Tuleb Jehoova nimel",
    "Juuda tuhandete seas",
    "Antipas",
    "kuulutamist seadustama",
    "elame, liigume ja oleme olemas",
    "sõnadest lõksu püüdma",
    "Sebna",
    "mõistis maailma süüdi",
    "Pääste me võlgneme",
    "Genneesareti järv",
    "Valvavad teie järele",
    "Läheb vaja tarkust",
    "Allutatud tühisusele",
    "Abija teenistusrühm",
    "Vähesest saab tuhat",
    "Sa lähed Jehoova ees",
    "võida kõige püham paik",
    "Heldai",
    "Toobia",
    "Jedaja",
    "Hoiablepingut jõus veel ühe nädala",
    "7 nädalat ja veel 62 nädalat",
    "Jehoova tõttab sellega omal ajal",
    "Zeenas",
    "Šaul",
    "Quirinius",
    "Nooled sangari käes",
    "Nähtamatu Jumala peegeldus",
    "See kel on mõjuvõimu",
    "Jõu ja kaine mõistuse vaim",
    "Mida saab inimene mulle teha?",
    "suur põlev mägi",
    "metsalise märk",
    "varustusevalvur",
    "kõigest pole kasu",
    "julge ja hästi tugev",
    "Valmidus kuulutada head sõnumit rahust",
    "Meeros",
    "Liisuosa päevade lõpus",
    "Miikaja",
    "Naerab hirmu üle",
    "pole teadmisi ega tarkust",
    "Toetub inimkäele",
    "Herodias",
    "ristib püha vaimu ja tulega",
    "Arpaksad",
    "Serah",
    "pidagu sügavalt lugu",
    "Täidab Jumala tahet",
    "Käsitleb tõe sõna õigesti",
    "vastu pidades vilja kannavad",
    "Diotrefes",
    "kõrgus ega sügavus",
    "kuningriigi võtmed",
    "kutsun päikesetõusu poolt röövlinnu",
    "kuulutan millega asjad lõppevad",
    "ammusest ajast",
    "variseride juuretis",
    "kõike seda muud antakse teile",
    "teise vahikorra ajal",
    "valmistab katsumuse korral väljapääsu",
    "ei otsi austust inimestelt",
    "pärib teilt teie lootuse kohta",
    "võtted pole meile teadmata",
    "kolmandik taevatähtedest",
    "Poeg allutab end Jumalale",
    "Ärge petke end",
    "ustavad selle maailma vara kasutamises",
    "elab igavesest ajast igavesti",
    "vangistame iga mõtte",
    "must mooruspuu",
    "Kasvata meie usku",
    "Sinu usk on sind terveks teinud",
    "sadas tuld ja väävlit",
    "pearahamaks",
    "paneb õiguse võidutsema",
    "Trüfaina",
    "isandate isand",
    "kuningate kuningas",
    "rahvastele määratud ajad",
    "Olge alati rõõmsad",
    "Alfeus",
    "Taeva vägesid kõigutatakse",
    "mere möirgamine",
    "olukorrast väljapääsu",
    "Kasvavad koos lõikuseni",
    "Võtke oma koht sisse",
    "seiske ja vaadake, kuidas Jehoova teid päästab",
    "Kristusega seadus lõppes",
    "jäädav vägi ja jumalikkus",
    "Massa ja Meriba",
    "hea, meeldiv ja täiuslik",
    "imelise lootuse täitumine",
    "Vastab enne faktide ärakuulamist",
    "Siiba",
    "Jehoova soosingu aasta",
    "templipühitsemispüha",
    "Tuleb öö, mil keegi ei saa midagi teha",
    "Toida mu lambakesi",
    "inimene on valitsenud inimese üle",
    "ühtsuse täiuslik side",
    "Kes hüüab appi Jehoova nime, päästetakse",
    "on iga maja kellegi ehitatud",
    "Amittai",
    "õiguse parema käega",
    "peitis end ära",
    "läksie vaatama",
    "tõesti leiaksid ta",
    "suurima patuse näite varal",
    "Ei suuda meid lahutada Jumala armastusest",
    "Diotrefes",
    "käesolev ega tulev",
    "mistahes muu loodu",
    "kui ma kuulen oma lapsi tõeteel käivat",
    "Ebed-Melek",
    "Nebusaradan",
    "Alguses lõi Jumal taeva ja maa",
    "tulen kiiresti",
    "Isand Jeesus Kristuse arm olgu pühadega!",
    "Jisreel",
    "Ärge kaotage julgust",
    "Ole julge ja tugev",
    "Ustavale oled sa ustav",
    "Barsillai",
    "tuleb aeg, ja see ongi juba käes",
    "Epafras",
    "veel julgemad, jah, kartmatud",
    "Seres",
    "Hadassa",
    "Tiberiase meri",
    "Sebedeus",
    "Justus",
    "Kidroni org",
    "Jumal on teinud ta nii isandaks kui ka messiaks",
    "imelise valguse käes",
    "Olete täitnud Jeruusalemma",
    "Eela org",
    "Heebrea keelt kõnelevad juudid",
    "Keel on tuli",
    "Gaza",
    "Pole nendega mingit pistmist"];