export const words2 = [
    "Saamuel",
    "vana kuub",
    "tiivulised",
    "mõõgatorked",
    "Vahemeri",
    "Apostlite teod",
    "küüslauk",
    "5 arukat neitsit",
    "Noa laev",
    "toored viinamarjad",
    "Siisera",
    "laevatükid",
    "rahetorm",
    "veevool katkeb",
    "Maa püsib igavesti",
    "Jeeriko",
    "Eenok",
    "Petlemm",
    "Sekem",
    "nädalatepüha",
    "kuningriik",
    "Edom",
    "4026 e.m.a",
    "liisu heitmine",
    "mõistujutt",
    "Õlimägi",
    "meelelahutus",
    "Abisai",
    "Benjamin",
    "Moabimaa",
    "kuldvasikas",
    "ling",
    "vastupidavus",
    "paabulinnud",
    "kuivanud viigipuu",
    "õli",
    "Saagu valgus",
    "manna",
    "Ärge muretsege",
    "Raahel",
    "vaimumõõk",
    "Oobed",
    "maavärin",
    "korv",
    "mõttega lugema",
    "Jehu",
    "tessalooniklastele",
    "lõõmavad hobused",
    "pottsepp",
    "Jeesuse lunastusohver",
    "mandlipuu õitseb",
    "nälg",
    "kannatlik",
    "70 jüngrit",
    "gibeonlased",
    "truu armastus",
    "Bartolomeus",
    "Aakan varastab",
    "Siioni mägi",
    "surematus",
    "Jefta",
    "taimetoit armastusega",
    "sünnib Petlemmas",
    "raudkepp",
    "Ristija Johannes",
    "Taavet tantsib",
    "Pilaatus",
    "Naabal",
    "Damaskus",
    "teised lambad",
    "Siinai mägi",
    "peaingel",
    "Jeruusalemma müürid",
    "hea ja halva tundmise puu",
    "kogu südamest ja hingest",
    "sääsed",
    "Nebukadnetsar",
    "tiivad",
    "kesköö",
    "rauast sääred",
    "rebane",
    "tuvimüüjad",
    "12 kivi",
    "Talle pulmad",
    "koguduseabiline",
    "janusena postil",
    "tänulik pidalitõbine",
    "järeltulija",
    "Johannes",
    "Aamos",
    "Kyros",
    "metsalise kuju",
    "Sakarja",
    "Jesaja prohvetikuulutus",
    "püha vaimu vilja tahud",
    "alfa ja oomega",
    "lohe",
    "ingel",
    "haputainas",
    "varas öösel",
    "Miikal",
    "Daan",
    "trepp",
    "Andreas",
    "sikk",
    "elupuu",
    "Naatanael",
    "ingel Gaabriel",
    "Naaman",
    "leviit",
    "esmatähtis",
    "rullraamat",
    "hiiglased",
    "veri uksepiitadel",
    "Lea ja Raahel",
    "põlevad nooled",
    "Gomorra",
    "Ai linn",
    "inimesepoeg",
    "Orpa",
    "Kaaleb",
    "mägi suitseb",
    "viigimarjapätsike",
    "aare savinõudes",
    "Juudas Iskariot",
    "Filippus",
    "noor Timoteos",
    "ebajumal",
    "Mordokai",
    "Keefas",
    "manna kõrbes",
    "koloslastele",
    "aeg rääkida",
    "mõistuse seadus",
    "Korneelius perega",
    "Ruuben",
    "Jaafet",
    "allumine",
    "3 meetrit pikk",
    "Jaakob",
    "Malaki",
    "unenägu",
    "Diina",
    "suur torm",
    "Saagu valgus",
    "Lea",
    "Maarja Magdaleena",
    "Jael",
    "eluvesi",
    "hing",
    "Madu pettis mind",
    "vastpöördunu",
    "nasiir",
    "ime",
    "joogiohver",
    "Ketuura",
    "piim ja mesi",
    "neli inglit",
    "tempel",
    "töölesundijad",
    "Eenok",
    "Marta",
    "seitse trompetit",
    "Ma ei naernud",
    "šaakal",
    "speltanisu",
    "Nimrod",
    "Absalom",
    "auhiilgus",
    "kõhus kibe",
    "Püsigem ärkvel",
    "70 aastanädalat",
    "veskikivi",
    "teine surm",
    "ülevaataja",
    "Suur Babülon",
    "Metuusala",
    "Lemek",
    "tasuta juua",
    "tulejärv",
    "mullaks sa saad",
    "Euodia",
    "Egiptus",
    "elupuu",
    "Egiptuse vaarao",
    "Assur",
    "ike",
    "viinamari",
    "Rooma",
    "Täitke maa...",
    "odralõikus",
    "lapsed kurjuses",
    "küljeluu",
    "Naatan",
    "Dorkas",
    "tõde",
    "surutõrs",
    "turteltuvid",
    "misjonär",
    "kaastöölised",
    "pärdikud",
    "kana kogub tibud",
    "seeravid",
    "kuke kiremine",
    "Suusa",
    "kuulutamine",
    "pilliroog",
    "607 e.m.a",
    "mälestusraamat",
    "Hesekiel",
    "Eesav",
    "merelaine",
    "Jordan",
    "Zeus",
    "õepoeg Markus",
    "rinnakilp",
    "Jehoova on armastus",
    "sinepiseema",
    "vutt",
    "filiplastele",
    "arst Luukas",
    "rikas",
    "filosoofia",
    "Raahab",
    "rohutirtsud",
    "jooksmine",
    "Nehemja",
    "vibu",
    "hea sõnum",
    "hundid lambanahas",
    "Pootifar",
    "mälestusõhtu",
    "okaskroon",
    "jaanalind",
    "headus",
    "Siilo",
    "Haam",
    "Mirjam",
    "tõevöö",
    "Jaah",
    "Apollos",
    "Tiitus",
    "Taaniel lõvide augus",
    "kalur",
    "muul",
    "mürk",
    "Ilmutuse raamat",
    "Gaad",
    "tulipunane lohe",
    "vahimees",
    "Stefanos",
    "kogudusetelk",
    "kobra",
    "Hoosea",
    "väike kari",
    "ihaldusväärne",
    "põlev põõsas",
    "aeg istuda",
    "maksude maksmine",
    "ristimine",
    "jänes",
    "karu",
    "Joosija",
    "õlipuuleht",
    "parmud",
    "Fileemon",
    "suur viletsus",
    "Bileam",
    "lilled",
    "halb variser",
    "sünagoog",
    "lehm",
    "Herodes",
    "Absalom",
    "eluraamat",
    "Jaakobus",
    "lõke",
    "koduloomad",
    "patud on erepunased",
    "Abigail",
    "Deliila",
    "puudesalu",
    "papüürus",
    "Sett",
    "sälg",
    "laisk ori",
    "iisop",
    "Uurija",
    "keerubid",
    "JHVH",
    "toonekurg",
    "eluleib",
    "valetamine",
    "Seeba kuninganna",
    "Moosese seadus",
    "preester",
    "järelnoppimine",
    "Jumala ilmutus",
    "muulane",
    "vaskmadu",
    "lõuna kuningas",
    "Eeli",
    "Seem",
    "ratsanik",
    "andestan",
    "Juuda",
    "inimesekartus",
    "kuulekus",
    "halb seltskond",
    "püha vaim",
    "Batseba",
    "Abner",
    "40 päeva",
    "Piinehas",
    "pull",
    "efeslastele",
    "Galilea",
    "valeprohvet",
    "metsaline",
    "süütud nagu tuvid",
    "Harmagedoon",
    "Soolameri",
    "juuksekarvad",
    "karikas",
    "purjetamine",
    "Laaban",
    "Jerobeam",
    "Siimeon",
    "Matteus",
    "vend Juudas",
    "Toomas",
    "Boas",
    "kadunud lammas",
    "Abinadab",
    "piik",
    "maksukoguja",
    "kristlased",
    "Niineve",
    "Punane meri",
    "1000 aastat",
    "usukilp",
    "Sippora",
    "Huur",
    "Betsaleel",
    "Huusai",
    "Saulus",
    "Miika",
    "Uri linn",
    "Juuda",
    "Samaaria",
    "rusuhunnik",
    "rahva juhid",
    "igaüks",
    "vilistid",
    "Amnon",
    "Samma",
    "päevad on kurjad",
    "halastus",
    "kõiksugused inimesed",
    "hea südametunnistus",
    "suguvõsa",
    "nöörlood",
    "nikerdatud kuju",
    "kogenematud lähevad edasi",
    "Betuel",
    "ärge ärritage",
    "koi ja rooste",
    "armetu inimene",
    "üürielamu",
    "õieke",
    "Sina üksi",
    "erapoolik",
    "otsuseorg",
    "kaks hooranaist",
    "puhtad ajendid",
    "Haagar",
    "Ismael",
    "Ketuura",
    "Baalak",
    "Süüria",
    "Meedia",
    "Ruuben",
    "kohaloleku tundemärk",
    "Gehenna",
    "Septuaginta",
    "tõotatud maa",
    "hautisepott",
    "Mefiboset",
    "Abiram",
    "Ei anna alla",
    "meeldiv",
    "patu seadus",
    "Jeremija",
    "Lüüdia",
    "taht",
    "harjutamise teel treenimine",
    "Joppe",
    "ülikud",
    "vabastusaasta",
    "jebuuslased",
    "Kapernauma",
    "ebaaus tulu",
    "keha treenimine",
    "seitse aega",
    "pisarad",
    "sõnaosav",
    "Kiis",
    "pelikan",
    "mürr",
    "vaskmeri",
    "tulevane elu",
    "Betsata tiik",
    "Tüüros",
    "puhkepaik",
    "Antiookia",
    "figuur",
    "nahast piimalähker",
    "käsi põues",
    "luurajad",
    "tamburiin",
    "suudlema",
    "vahionn",
    "lehvivad juuksed",
    "kurgipõld",
    "Justus",
    "lüüra",
    "piiramisrõngas",
    "püha mägi",
    "kullasepp",
    "aganad",
    "alusrõivas",
    "Aramea",
    "asasel",
    "batt",
    "Dekapolis",
    "ülesminekulaulud",
    "Hermes",
    "Tühi ja lage",
    "vetesügavus",
    "esimene päev",
    "koondunud veed",
    "proselüüt",
    "peltsebul",
    "sekt",
    "See oli väga hea",
    "kaarik",
    "vanne",
    "täiendus",
    "viljapeks",
    "Kolgata",
    "suulamlanna",
    "Karmel",
    "Hanna",
    "sinepiseeme",
    "alabasterpudel",
    "Areopaag",
    "Dareios",
    "Beltsassar",
    "Belsatsar",
    "juudi mehe kuub",
    "puu eluiga",
    "seeme tee ääres",
    "rändur",
    "peigmees",
    "Mattias",
    "maskil",
    "Gilead",
    "tumm Sakarjas",
    "Immaanuel",
    "kaduvuse orjus",
    "kõigekõrgema prohvet",
    "Jairus",
    "Sühhari linn",
    "käimla",
    "pesemata kätega söömine",
    "Nikodeemos",
    "paindlik",
    "Eliihu",
    "õhusuudlus",
    "lõunamaa kuninganna",
    "see põlvkond",
    "rästikute sugu",
    "uuesti sündima",
    "paljusid asju õpetama",
    "avaldama",
    "püha saladus",
    "ilmaaegu",
    "pöörduma",
    "teeäärne pinnas",
    "umbrohi",
    "tähekriipsuke",
    "aiataimed",
    "seaa",
    "rändkaupmees",
    "igasugused kalad",
    "tulekolle",
    "Uut ja vana",
    "puusepa poeg",
    "kodukant",
    "neli vankrit",
    "Võsu",
    "ülim isand",
    "lepingu saadik",
    "taevaluugid",
    "Jehoova tundmine",
    "Joosafat",
    "kroonikaraamat",
    "mälestus",
    "püha tee",
    "nimekad mehed",
    "häbitunne",
    "mässumeelsus",
    "võitma usule",
    "kadumatu ilu",
    "vooruslikkus",
    "algõpetus",
    "vundament",
    "röövlind",
    "päikesetõus",
    "peab vastu kõiges",
    "usub kõike",
    "toitu ostma",
    "täiel määral",
    "viivitamata",
    "Beroia",
    "siiras usk",
    "Teda kuulake",
    "lõplik võit",
    "surma maitsma",
    "keelas kõvasti",
    "määratud aeg",
    "igavik südames",
    "rahvavanemad",
    "residents",
    "asjatundja",
    "uus laul",
    "Siilas",
    "korraldus",
    "palvekoda",
    "suur pilv tunnistajaid",
    "võidujooks",
    "eesootav rõõm",
    "põhitõed",
    "piim ja tahke toit",
    "Jaabin",
    "Etteheiteid tegemata",
    "usu tõttu",
    "valged rüüd",
    "mõõtmatu",
    "põrm",
    "teab hästi",
    "hädaaeg",
    "Sinu sõna peale",
    "Ära karda",
    "On oma kohtadel",
    "Jumala seatuna",
    "eestvedajad",
    "allutama",
    "Iisraeli püha",
    "arukus",
    "arvutama",
    "666",
    "saate tõeliselt vabaks",
    "teraselt vaatama",
    "täiuslik seadus",
    "Kaisarea",
    "mägismaa",
    "inimsüda",
    "ülimalt õnnistatu",
    "Jehoova orjatar",
    "leopard",
    "Elatanu",
    "Sarv rääkis",
    "tervituse hääl",
    "Isanda ema",
    "tuvipoeg",
    "vastsündinu",
    "šaakalid",
    "žestid",
    "Akvila",
    "külitama",
    "lõid käed",
    "palehigis",
    "Uus Jeruusalemm",
    "tollihoone",
    "mereloomad",
    "laubavõru",
    "sajapealikud",
    "käekäik",
    "elavate maa",
    "meeleheide",
    "valearutlused",
    "korra kummardad",
    "mõtlemisoskus",
    "lugupidamatu",
    "haistma",
    "lehviv lakk",
    "vägevus",
    "kartmatud",
    "deemonite sõnumid",
    "Ärge imestage",
    "kohkuma",
    "noor tugev lõvi",
    "neitsilik tütar",
    "kustutamatu tuli",
    "judaism",
    "kodakondsus",
    "rusutud",
    "rõõmus süda",
    "alati pidu",
    "hea maa",
    "telgitegijad",
    "koormaloom",
    "pesakond",
    "sähviv tuli",
    "sädelev jää",
    "ämm",
    "minia",
    "raju",
    "kaks leptonit",
    "mõõtmatu",
    "goferipuu",
    "koormavad lohutajad",
    "salv",
    "ait",
    "teised rahvad",
    "silmapiir",
    "säästma",
    "vastupanija",
    "taevased paigad",
    "koosseis",
    "energia",
    "äravalitud",
    "uueksloomine",
    "rabatud",
    "Kreeta",
    "Kõuepojad",
    "ilmalik",
    "sirutab tiivad",
    "täielik rõõm",
    "väljuv jõud",
    "teie päralt",
    "kindel alus",
    "vendade süüdistaja",
    "tähekriipsuke",
    "põhimõte",
    "avalik",
    "eriline omand",
    "hoiatav näide",
    "Patmos",
    "fakt",
    "majaperenaine",
    "aianuga",
    "viimseil päevil",
    "viimseil päevil",
    "patte kahetsema",
    "tõeline elu",
    "sõitlema",
    "vaistlikult",
    "veeta pilved",
    "vandenõu",
    "Ismael",
    "veemahuti",
    "üürike aega",
    "hiidtürannid",
    "verepõld",
    "asendama",
    "kosutuse ajad",
    "Oma õpetus",
    "Safiira",
    "hajutama",
    "ahtake värav",
    "isakodu",
    "ärakiri",
    "salakaval",
    "siirus",
    "selgitades loogiliselt",
    "niinimetatud"
  ];