export const words1 = [
    "Aabraham", "Bileam", "Jefta",
    "Iisak", "kaev", "lammas",
    "laulma", "Aabel", "sõna",
    "suur kala", "siga", "deemonid",
    "toit", "Taavet", "vesi",
    "Joosua", "kuu", "poiss",
    "käsi", "kuld", "kits",
    "tütar", "Kain", "Simson",
    "Saul", "kõrb", "lootus",
    "Rebeka", "Saara", "Maarja",
    "Ester", "mesi", "töö",
    "metsloomad", "madu", "täht",
    "Eeva", "valgus", "õun",
    "Maarja", "silm", "ronk",
    "hobune", "Laulud", "Iiob",
    "tall", "suu", "veeuputus",
    "ema", "sõrm", "Noa",
    "suur lohe", "arbuus", "tiik",
    "paat", "Giideon", "lõvi",
    "kana", "Paulus", "kotkas",
    "Jehoova", "keerub", "rahu",
    "vikerkaar", "Saalomon", "Piibel",
    "Taaniel", "torn", "paradiis",
    "lapsed", "õhtu", "Aadam",
    "sipelgas", "palve", "Rutt",
    "puu", "Joona", "patt",
    "kuningas", "meri", "aamen",
    "eesel", "Koljat", "Saul",
    "Joosep", "Aaron", "riided",
    "Jeesus", "mees", "leib",
    "armastus", "päike", "naer",
    "kaamel", "kaev", "pimedus",
    "nutt", "kepp", "Matteus",
    "liiv", "Mooses", "lamp",
    "Leevi", "Iisebel", "maakera",
    "apostel", "Noomi", "Lott",
    "tuvi", "2. Ajaraamat", "kõrv",
    "halb", "sool", "hommik",
    "piim", "Peetrus", "varblane",
    "jõgi", "Kristus", "Iiob",
    "konnad", "liha", "Joonatan",
    "Iisai", "järv", "Markus",
    "Johannes", "Iisrael", "rohi",
    "kadedus", "päästja", "rada",
    "uss", "Jaakob", "messias",
    "Jumala nimi", "auline", "eeskuju",
    "imik", "rõõm", "süda",
    "veri", "vilistasid", "välk",
    "väle", "kuiv", "seeme",
    "nina", "muld", "ilus",
    "ahi", "aastaaeg", "leht",
    "täiskuu", "kuninganna", "naba",
    "pill", "arm", "lehm",
    "voodi", "tuvimaja", "sinikad",
    "hapu", "maja", "raha",
    "hallid juuksed", "vili", "telk",
    "tähnilised", "nägu", "janu",
    "magama", "lõhn", "vai",
    "ling", "kingitus", "vasar",
    "post", "tuul", "vana",
    "vihm", "tõrvik", "suur täht",
    "kõne", "kari", "post",
    "möll", "sarv", "õigus",
    "kari", "vaim", "ustav",
    "sõprus", "koer", "tuli",
    "auhind", "pääste", "Jumal",
    "juur", "ohakas", "sajakordne",
    "kõrvad", "vaenlane", "õnnetus",
    "hüppama", "kausike", "tee",
    "elu", "tõde", "häbi",
    "ingel", "talv", "suvi",
    "külm", "kuum", "oda"
  ];